server:
  port: 7003

eureka:
  server:
   enable-self-preservation: true
   eviction-interval-timer-in-ms: 10000
  instance:
   hostname: eureka7003.com
  client:
   healthcheck: 
    enabled: true
   register-with-eureka: false
   fetch-registry: false
   service-url:
    defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/