server:
  port: 8103

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cloud.org.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
   name: cloud-dept
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://47.92.81.255:5432/business
   username: jubaoadmin123
   password: junbao@123
   dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200
    

eureka:
   client:
      healthcheck: 
         enabled: true
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 10
      instance-id: dept-database-operate-03
      prefer-ip-address: true
      
      
info:
   app.name: xiaoyao-cloud-producer
   company.name: playstation
   build.artifactId: $project.artifactId$
   build.version: $project.version$