server:
   port: 9527
   
   
spring:
   application:
      name: cloud-zuul-gateway
      
zuul:
   prefix: /hist
   ignored-services: "*"
   routes:
      mydept.serviceId: cloud-dept
      mydept.path: /mydept/**


eureka:
   client:
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true
      
      
info:
   app.name: xiaoyao-cloud-gateway
   company.name: gateway
   build.artifactId: cloud-zuul-gateway
   build.version: 0.0.1-SNAPSHOT